41 add camera to beamng scenario
ChristianBirchler/sdc-scissor pull request #46
Opened 2022-06-04 09:11 UTC by tanzilkm

2022-06-04 09:16 UTC, tanzilkm commented
Hi @ChristianBirchler , 
Can you please review and merge Parameterize Camera Field of view 


Thanks 
Tanzil

2022-06-07 08:45 UTC, ChristianBirchler requested changes
Ensure all variables in constructors are somewhere defined. I will also add some configs for linters so that you can check the code style before you do a pull request.

2022-06-07 08:45 UTC, ChristianBirchler commented on sdc-scissor.py
> +@click.option('-fov','--field-of-view', default=120, type=click.INT)
where is the argument in the function signature?

2022-06-07 08:45 UTC, ChristianBirchler commented on sdc-scissor.py
> +
remove empty line

2022-06-07 08:45 UTC, ChristianBirchler commented on sdc-scissor.py
> +    beamng_simulator = SimulatorFactory.get_beamng_simulator(home=home, user=user, rf=rf, max_speed=max_speed, fov=field_of_view)
do not exceed 120 characters per line. I will add a configuration files for linters so that you can check the code.

2022-06-07 08:45 UTC, ChristianBirchler commented on sdc_scissor/simulator_api/beamng_simulator.py
> +        self.fov = fov
where is `fov` in the signature?

2022-06-07 08:45 UTC, ChristianBirchler commented on sdc_scissor/simulator_api/beamng_simulator.py
> +        self.camera = BeamNGCamera(self.beamng, 'brewer_camera',fov=self.fov)
add whitespace after comma

2022-06-07 12:53 UTC, ChristianBirchler approved these changes
Everything looks good.

2022-06-07 12:53 UTC, merged