add Tree to Scenario
ChristianBirchler/sdc-scissor pull request #50
Opened 2022-06-07 16:05 UTC by tanzilkm

Hey @ChristianBirchler, 
Can you please review adding trees obstacles to scenario 

Thanks 
Tanzil

2022-06-08 16:29 UTC, ChristianBirchler requested changes
Format the code as follow:
```

poetry run black -C -l 120 .
```

2022-06-09 10:02 UTC, ChristianBirchler requested changes

2022-06-09 10:02 UTC, ChristianBirchler commented on sdc-scissor.py
> +@click.option("--tree-dist", default=5, type=click.INT)
The order is not correct. It must be the last option since you put the `tree_dist` argument as last argument in the function signature

2022-06-09 11:15 UTC, ChristianBirchler commented
> SonarCloud Quality Gate failed.    [![Quality Gate failed](https://camo.githubusercontent.com/4ea51c1f64ee3746f631653a02ab678ca6a3efb5f5cb474402faed2e3dcf90b5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f6661696c65642d313670782e706e67)](https://sonarcloud.io/dashboard?id=ChristianBirchler_sdc-scissor&pullRequest=50)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=ChristianBirchler_sdc-scissor&pullRequest=50&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=ChristianBirchler_sdc-scissor&pullRequest=50&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=ChristianBirchler_sdc-scissor&pullRequest=50&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=ChristianBirchler_sdc-scissor&pullRequest=50&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=ChristianBirchler_sdc-scissor&pullRequest=50&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=ChristianBirchler_sdc-scissor&pullRequest=50&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=ChristianBirchler_sdc-scissor&pullRequest=50&resolved=false&types=SECURITY_HOTSPOT) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=ChristianBirchler_sdc-scissor&pullRequest=50&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=ChristianBirchler_sdc-scissor&pullRequest=50&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=ChristianBirchler_sdc-scissor&pullRequest=50&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=ChristianBirchler_sdc-scissor&pullRequest=50&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=ChristianBirchler_sdc-scissor&pullRequest=50&resolved=false&types=CODE_SMELL)
> 
> [![0.0%](https://camo.githubusercontent.com/3f04cff3eeef8477afe696ae55c570cbb6ed02f16152497c14251828329a3e91/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f302d313670782e706e67)](https://sonarcloud.io/component_measures?id=ChristianBirchler_sdc-scissor&pullRequest=50&metric=new_coverage&view=list) [0.0% Coverage](https://sonarcloud.io/component_measures?id=ChristianBirchler_sdc-scissor&pullRequest=50&metric=new_coverage&view=list) [![0.0%](https://camo.githubusercontent.com/8047c63e1f9ed03f63001e1eadce4676bade3e0f83ec690a9c625287796248a6/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332d313670782e706e67)](https://sonarcloud.io/component_measures?id=ChristianBirchler_sdc-scissor&pullRequest=50&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=ChristianBirchler_sdc-scissor&pullRequest=50&metric=new_duplicated_lines_density&view=list)

The quality gate failed but I guess if you add just a simple test case that covers some lines of your new code then it will pass since I put the quality gate very low (1% coverage I guess). In general, it is good practice to provide also some test code to every pull request.

2022-06-10 13:40 UTC, ChristianBirchler commented
Currently the CI pipeline is failing since poetry is not able to install the requirements of PyPI. I don't exactly know yet what was happening but I guess it is an networking issue that was not caused by us but do you @tanzilkm know what's up with PyPI?

2022-06-11 13:25 UTC, tanzilkm commented
Hi @ChristianBirchler, 
I had previously experience this issue with git action. It  is downtime of git action. I had rerun all the failed action and it was successful without any modification  ;)

2022-06-27 07:57 UTC, ChristianBirchler commented
> Hi @ChristianBirchler, I had previously experienced this issue with git action. It is downtime of git action. I had rerun all the failed action, and it was successful without any modification ;)

Everything works now again with GitHub actions. However, please add at least some test code for each pull request so that the quality gate on SonarCloud is passed.

2022-07-08 09:54 UTC, merged